"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { useSession } from "next-auth/react";
import { CheckCircle2, Loader2, MessageCircle, Star, ThumbsUp, UserCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";

const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:5000";
interface Review { id: string; userId: string; rating: number; title: string; body: string; usageStatus: number; isVerified: boolean; helpfulCount: number; isHelpful: boolean; isMine: boolean; createdAtUtc: string; }
interface ReviewSet { averageRating: number; reviewCount: number; items: Review[] }
interface Changelog { id: string; version: string; title: string; body: string; publishedAtUtc: string; }

export function ProductCommunityPanel({ productId, productSlug }: { productId: string; productSlug: string }) {
  const { data: session } = useSession(); const accessToken = session?.accessToken as string | undefined;
  const [tab, setTab] = useState<"reviews" | "changelog">("reviews"); const [reviews, setReviews] = useState<ReviewSet>({ averageRating: 0, reviewCount: 0, items: [] }); const [changelog, setChangelog] = useState<Changelog[]>([]);
  const [draft, setDraft] = useState({ rating: 5, title: "", body: "", usageStatus: 0 }); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const load = useCallback(async () => { const headers = accessToken ? { Authorization: `Bearer ${accessToken}` } : undefined; const [reviewResponse, changelogResponse] = await Promise.all([fetch(`${API_URL}/api/products/${productId}/reviews`, { headers, cache: "no-store" }), fetch(`${API_URL}/api/products/${productId}/changelog`, { cache: "no-store" })]); if (reviewResponse.ok) setReviews(await reviewResponse.json()); if (changelogResponse.ok) setChangelog(await changelogResponse.json()); }, [accessToken, productId]);
  useEffect(() => {
    // Product/session changes intentionally refresh the community snapshot.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void load();
  }, [load]);
  const submit = async () => { if (!accessToken) return; setSaving(true); setError(""); try { const response = await fetch(`${API_URL}/api/products/${productId}/reviews/me`, { method: "PUT", headers: { Authorization: `Bearer ${accessToken}`, "Content-Type": "application/json" }, body: JSON.stringify(draft) }); if (!response.ok) { const data = await response.json().catch(() => null) as { detail?: string } | null; throw new Error(data?.detail ?? "Review kaydedilemedi."); } setDraft({ rating: 5, title: "", body: "", usageStatus: 0 }); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Review kaydedilemedi."); } finally { setSaving(false); } };
  const helpful = async (reviewId: string) => { if (!accessToken) return; await fetch(`${API_URL}/api/reviews/${reviewId}/helpful`, { method: "PUT", headers: { Authorization: `Bearer ${accessToken}` } }); await load(); };
  return <section className="overflow-hidden rounded-3xl border bg-card"><div className="flex border-b"><button onClick={() => setTab("reviews")} className={`flex-1 px-5 py-4 text-sm font-bold ${tab === "reviews" ? "border-b-2 border-primary text-primary" : "text-muted-foreground"}`}>Review’lar ({reviews.reviewCount})</button><button onClick={() => setTab("changelog")} className={`flex-1 px-5 py-4 text-sm font-bold ${tab === "changelog" ? "border-b-2 border-primary text-primary" : "text-muted-foreground"}`}>Changelog ({changelog.length})</button><Link href={`/p/${productSlug}`} className="flex flex-1 items-center justify-center gap-2 px-5 py-4 text-sm font-bold text-muted-foreground hover:text-primary"><MessageCircle className="h-4 w-4" /> Ürün forumu</Link></div>
    {tab === "reviews" ? <div className="p-6"><div className="mb-6 flex items-center gap-4 rounded-2xl bg-amber-500/5 p-5"><div className="text-4xl font-black">{reviews.averageRating || "—"}</div><div><div className="flex text-amber-500">{[1,2,3,4,5].map(value => <Star key={value} className={`h-5 w-5 ${value <= Math.round(reviews.averageRating) ? "fill-current" : "opacity-25"}`} />)}</div><p className="mt-1 text-xs text-muted-foreground">{reviews.reviewCount} doğrulanabilir kullanıcı deneyimi</p></div></div>
      {accessToken && <div className="mb-7 space-y-3 rounded-2xl border p-4"><div className="flex flex-wrap gap-2">{[1,2,3,4,5].map(value => <button key={value} onClick={() => setDraft(current => ({ ...current, rating: value }))}><Star className={`h-6 w-6 text-amber-500 ${value <= draft.rating ? "fill-current" : "opacity-25"}`} /></button>)}<select value={draft.usageStatus} onChange={event => setDraft(current => ({ ...current, usageStatus: Number(event.target.value) }))} className="ml-auto rounded-lg border bg-background px-3 text-sm"><option value={0}>Kullanıyorum</option><option value={1}>Daha önce kullandım</option><option value={2}>Deniyorum</option></select></div><Input value={draft.title} onChange={event => setDraft(current => ({ ...current, title: event.target.value }))} placeholder="Deneyimini özetle" /><Textarea value={draft.body} onChange={event => setDraft(current => ({ ...current, body: event.target.value }))} placeholder="Neyi iyi, neyi geliştirilebilir buldun?" />{error && <p className="text-sm text-destructive">{error}</p>}<Button onClick={submit} disabled={saving || draft.title.trim().length < 3 || draft.body.trim().length < 10}>{saving && <Loader2 className="animate-spin" />} Review’ı yayınla</Button></div>}
      <div className="space-y-3">{reviews.items.map(item => <article key={item.id} className="rounded-2xl border p-5"><div className="flex items-start justify-between gap-3"><div><div className="flex text-amber-500">{[1,2,3,4,5].map(value => <Star key={value} className={`h-4 w-4 ${value <= item.rating ? "fill-current" : "opacity-20"}`} />)}</div><h3 className="mt-2 font-black">{item.title}</h3></div>{item.isVerified && <span className="flex items-center gap-1 text-xs font-bold text-emerald-600"><UserCheck className="h-4 w-4" /> Doğrulandı</span>}</div><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-muted-foreground">{item.body}</p><Button variant="ghost" size="sm" className="mt-3" onClick={() => helpful(item.id)} disabled={!accessToken || item.isMine}><ThumbsUp className={item.isHelpful ? "fill-current" : ""} /> Faydalı ({item.helpfulCount})</Button></article>)}{reviews.items.length === 0 && <p className="py-8 text-center text-sm text-muted-foreground">Henüz review yok. İlk deneyimi sen paylaş.</p>}</div></div> :
      <div className="space-y-4 p-6">{changelog.map(item => <article key={item.id} className="relative border-l-2 border-primary/30 pl-6"><span className="absolute -left-2 top-1 h-3.5 w-3.5 rounded-full bg-primary ring-4 ring-background" /><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-primary/10 px-2 py-0.5 text-xs font-black text-primary">{item.version}</span><span className="text-xs text-muted-foreground">{new Date(item.publishedAtUtc).toLocaleDateString("tr-TR")}</span></div><h3 className="mt-2 text-lg font-black">{item.title}</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-muted-foreground">{item.body}</p></article>)}{changelog.length === 0 && <div className="py-10 text-center text-muted-foreground"><CheckCircle2 className="mx-auto mb-3 h-9 w-9 opacity-30" /><p>Henüz changelog paylaşılmadı.</p></div>}</div>}
  </section>;
}
